server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    username: root
    password: 9421
    url: jdbc:mysql://localhost:3306/mytest
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml